### ISSUE TITLE
PlotlyJS not working for HTML output

### ISSUE THREAD

**Issue by MHellmund** [PumasAI/QuartoNotebookRunner.jl#129]
Problem:
test.qmd:
`````
---
engine: julia
---

```{julia}
using PlotlyJS

plot(rand(10,4))
```
`````

`$ quarto render test.qmd --to html`
load `test.html` in browser  ==>  *no plot, error in javascript console:* `require not defined`

 - Solution A:  change "require" to "cdn" here: https://github.com/PumasAI/QuartoNotebookRunner.jl/blob/main/src/worker.jl#L815

- Solution B: Quarto has this mechanism: https://github.com/quarto-dev/quarto-cli/blob/main/src/core/jupyter/widgets.ts#L102-L105 but at the moment this is not triggered by the julia engine.

**Comment by MichaelHatherly** [comment]
Could you provide the `test.html` output that's failing, I've not managed to reproduce that myself @MHellmund.

**Comment by MHellmund** [comment]
[test.zip](https://github.com/PumasAI/QuartoNotebookRunner.jl/files/15395819/test.zip)
produced as described above with 
quarto 1.5.32, 
julia 1.10.3, 
 julia env includes PlotlyJS.jl 0.18.13

**Comment by MichaelHatherly** [comment]
@MHellmund the workaround for now (if you've not done it already) would of course just be to include `requirejs` in the notebook frontmatter

```yaml
include-in-header:
    text: |
        <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```
