### ISSUE TITLE
Take environment variables directly from the `_environment` file

### ISSUE THREAD

**Issue by albertomercurio** [PumasAI/QuartoNotebookRunner.jl#217]
Following [this page](https://quarto.org/docs/projects/environment.html) on the official documentation of Quarto, it is possible to define environment variables directly inside the `_environment` file. This is very useful when we need to define many variables used on many files.

Apparently, the only way that works so far is by writing the following yaml in each file

```yaml
engine: julia
julia:
    env: ["JULIA_NUM_THREADS=16", "JULIA_CONDAPKG_BACKEND=Null", "JULIA_PYTHONCALL_EXE=../pyenv/bin/python"]
```
